version: "3.9"

networks:
  local:

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - app1
      - app2
    networks:
      - local

  app1:
    build: ./app
    hostname: app1
    command: npm run app
    volumes:
      - ./app:/home/node/app
    networks:
      - local

  app2:
    build: ./app
    hostname: app2
    command: npm run app
    volumes:
      - ./app:/home/node/app
    networks:
      - local

  app:
    build: ./app
    hostname: app
    command: npm run app
    volumes:
      - ./app:/home/node/app
    ports:
      - 3000:3000

  app-clustered:
    build: ./app
    hostname: app
    command: npm run app:clustered
    volumes:
      - ./app:/home/node/app
    ports:
      - 3000:3000
